/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'root' at '06.01.16 21:46' with Gradle 2.6
 *
 * @author root, @date 06.01.16 21:46
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
